FROM ubuntu:latest

RUN apt-get update && apt-get install -y nodejs npm

WORKDIR /nftmint-contract

RUN rm -rf ./*

COPY package*.json /nftmint-contract/

RUN npm install

COPY src /nftmint-contract/src/

RUN npm run buildLinux
